FROM jenkins/inbound-agent

USER root

RUN apt-get update && apt-get install -y \
    docker.io \
    git \
    python3 \
    python3-pip \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN usermod -aG docker jenkins

USER jenkins

RUN curl -LsSf https://astral.sh/uv/install.sh | sh

ENV PATH="/home/jenkins/.local/bin:${PATH}"

# dat to vyssie? pred alebo za USER jenkins riadok
WORKDIR /home/jenkins/agent 