FROM jenkins/inbound-agent

USER root

# Install basic dependencies
RUN apt-get update && apt-get install -y \
    git \
    python3 \
    python3-pip \
    curl \
    gosu \
    ca-certificates \
    gnupg \
    lsb-release \
    && rm -rf /var/lib/apt/lists/*

# Docker CLI (without daemon)
RUN install -m 0755 -d /etc/apt/keyrings \
    && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg \
    && chmod a+r /etc/apt/keyrings/docker.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null \
    && apt-get update \
    && apt-get install -y docker-ce-cli \
    # cleanup 
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN echo "jenkins ALL=(ALL) NOPASSWD: /bin/chown root\:docker /var/run/docker.sock, /bin/chmod 660 /var/run/docker.sock" > /etc/sudoers.d/jenkins-docker \  
    && chmod 0440 /etc/sudoers.d/jenkins-docker

RUN usermod -aG docker jenkins

USER jenkins

RUN curl -LsSf https://astral.sh/uv/install.sh | sh

ENV PATH="/home/jenkins/.local/bin:${PATH}"

WORKDIR /home/jenkins/agent

# Copy universal entrypoint script and set permissions
COPY scripts/jenkins-agent-entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

# Entrypoint - fixes docker.sock permissions, then runs agent as jenkins user
ENTRYPOINT ["/entrypoint.sh"]